version: '3.8'

services:
  user:
    build:
      context: .
      dockerfile: services/user/Dockerfile
    container_name: user_service
    ports:
      - "8080:8080"
    env_file:
      - ./services/user/.env
    depends_on:
      - postgres
      
    restart: unless-stopped  


  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      - POSTGRES_DB=ecommercecont   
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped


volumes:
  postgres_data: