version: '3.8'

services:
  user_service:
    build:
      context: .
      dockerfile: services/user/Dockerfile
    container_name: user_service
    ports:
      - "8080:8080"
    env_file:
      - ./services/user/.env
    depends_on:
      - user_postgres_db
      
    restart: unless-stopped  


  product_service:
    build:
      context: .
      dockerfile: services/product/Dockerfile
    container_name: product_service
    ports:
      - "8081:8081"
    env_file:
      - ./services/product/.env
    depends_on:
      - product_postgres_db
      
    restart: unless-stopped  


  order_service:
    build:
      context: .
      dockerfile: services/order/Dockerfile
   
    container_name: order_service
    ports:
      - "8082:8082"
    env_file:
      - ./services/order/.env  

    depends_on:
      - order_postgres_db
      - user_service
      - product_service
      

    restart: unless-stopped  



  payment_service:
    build:
      context: .
      dockerfile: services/payment/Dockerfile
   
    container_name: payment_service
    ports:
      - "8082:8082"
    env_file:
      - ./services/payment/.env  

    depends_on:
      - payment_postgres_db
      - order_service
      

    restart: unless-stopped  




  user_postgres_db:
    image: postgres:16
    container_name: user_postgres_db
    environment:
      - POSTGRES_DB=ecommerce_user   
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    ports:
      - "5432:5432"
    volumes:
      - user_postgres_data:/var/lib/postgresql/data


  product_postgres_db:
    image: postgres:16
    container_name: product_postgres_db
    environment:
      - POSTGRES_DB=ecommerce_product 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    ports:
      - "5433:5432"
    volumes:
      - product_postgres_data:/var/lib/postgresql/data    


  order_postgres_db:
    image: postgres:16
    container_name: order_postgres_db
    environment:
      - POSTGRES_DB=ecommerce_order
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    ports:
      - "5434:5432"
    volumes:
      - order_postgres_data:/var/lib/postgresql/data  


  payment_postgres_db:
    image: postgres:16
    container_name: payment_postgres_db
    environment:
      - POSTGRES_DB=ecommerce_payment
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    ports:
      - "5435:5432"
    volumes:
      - payment_postgres_data:/var/lib/postgresql/data           



  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - user_postgres_db
      - product_postgres_db
      - order_postgres_db
      - payment_postgres_db      
    restart: unless-stopped



  dbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: dbeaver
    environment:
      CB_ADMIN_NAME: adminadmin
      CB_ADMIN_PASSWORD: AdminAdmin123
      CB_SERVER_PORT: 8978
    ports:
      - "5051:8978"
    depends_on:
      - user_postgres_db
      - product_postgres_db
      - order_postgres_db
      - payment_postgres_db       
    restart: unless-stopped    



volumes:
  user_postgres_data:
  product_postgres_data:
  order_postgres_data:
  payment_postgres_data:  


